services:
  userservice:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    container_name: userservice
    ports:
      - "${USER_SERVICE_PORT}:80"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  gameservice:
    build:
      context: .
      dockerfile: src/GameService/Dockerfile
    container_name: gameservice
    ports:
      - "${GAME_SERVICE_PORT}:80"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  leaderboardservice:
    build:
      context: .
      dockerfile: src/LeaderboardService/Dockerfile
    container_name: leaderboardservice
    ports:
      - "${LEADERBOARD_SERVICE_PORT}:80"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  notificationservice:
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    container_name: notificationservice
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:80"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  statisticsservice:
    build:
      context: .
      dockerfile: src/StatisticsService/Dockerfile
    container_name: statisticsservice
    ports:
      - "${STATISTICS_SERVICE_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  apigateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "${API_GATEWAY_PORT}:80"
    depends_on:
      - userservice
      - gameservice
      - leaderboardservice
      - notificationservice
      - statisticsservice
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "${SQL_PORT}:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"

networks:
  default:
    name: gamehub-network
